apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels: { app: order-service }
  template:
    metadata:
      labels: { app: order-service }
    spec:
      containers:
        - name: order-service
          image: <YOUR_REGISTRY>/order-service:1.0.0   # PLACEHOLDER
          ports: [{ containerPort: 8081 }]
          env:
            - name: DB_HOST
              value: orders-db
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef: { name: order-db-secret, key: password }
            - name: KAFKA_BOOTSTRAP
              value: kafka:9092
            - name: EUREKA_URI
              value: http://discovery-server:8761/eureka
          resources:
            requests: { cpu: 250m, memory: 512Mi }
            limits:   { cpu: "1",  memory: 1Gi }
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 8081 }
            initialDelaySeconds: 20
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: 8081 }
            initialDelaySeconds: 40
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ecommerce
spec:
  selector: { app: order-service }
  ports: [{ port: 8081, targetPort: 8081 }]
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: order-service
  namespace: ecommerce
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: { type: Utilization, averageUtilization: 70 }
